### ISSUE TITLE
Start behaviours with an associated set of waypoints

### ISSUE THREAD

**Issue by kragniz** [boatd/boatd#46]
It might be nice to optionally be able to tell boatd to load a set of waypoints if it starts a certain behaviour.

Maybe something similar to:

```yaml
behaviours:
    - behaviour:
        file: ~/git/boatd/behaviour.py
        waypoints:
            - [0.0002, 0.002]
            - [0.0005, 0.01]
            - [0.0001, 0.0001]
```
