### ISSUE TITLE
Allow disabling a plugin without removing the config from config

### ISSUE THREAD

**Issue by kragniz** [boatd/boatd#47]
Something like:

```yaml
plugins:
    - logger:
        enabled: true
        period: 10
        filename: logs/log_trace
```

and also

```yaml
plugins:
    - logger:
        enabled: false
        period: 10
        filename: logs/log_trace
```
